# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: tyke-exam
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:*'

#serverless config credentials --provider aws --key AKIAIOSFODNN7EXAMPLE --secret wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

functions:
  createDevice:
    handler: handler.createDevice
    events:
      - http:
          path: /devices
          method: post
          cors: true
  getDevice:
    handler: handler.getDevice
    events:
      - http:
          path: /devices/{id}
          method: get
          cors: true
  updateDevice:
    handler: handler.updateDevice
    events:
      - http:
          path: /devices/
          method: put
          cors: true
  deleteDevice:
    handler: handler.deleteDevice
    events:
      - http:
          path: /devices/{id}
          method: delete
          cors: true
  getHundredDevices:
    handler: handler.getHundredDevices
    events:
      - http:
          path: /devices/
          method: get
          cors: true
#
plugins:
  - serverless-offline